namespace XamlToolkit.WinUI.Controls
{
    runtimeclass EqualPanel : Microsoft.UI.Xaml.Controls.Panel
    {
        EqualPanel();

        Microsoft.UI.Xaml.Controls.Orientation Orientation;
        static Microsoft.UI.Xaml.DependencyProperty OrientationProperty{ get; };

        Double Spacing;
        static Microsoft.UI.Xaml.DependencyProperty SpacingProperty{ get; };
    }
}
