namespace XamlToolkit.WinUI.Animations
{
    /// <summary>
    /// A marker interface indicating that an object is a timeline animation.
    /// This is used for type detection since ITimeline is a C++ interface only.
    /// </summary>
    interface ITimelineMarker
    {
    };

    /// <summary>
    /// A marker interface indicating that an object is an attached timeline animation.
    /// This is used for type detection since IAttachedTimeline is a C++ interface only.
    /// </summary>
    interface IAttachedTimelineMarker
    {
    };
}
