namespace XamlToolkit.Labs.WinUI
{
    [default_interface]
    [createfromstring("XamlToolkit.Labs.WinUI.DoubleVector.CreateFromString")]
    runtimeclass DoubleVector : Windows.Foundation.Collections.IVector<Double>
    {
        DoubleVector();

        DoubleVector(Windows.Foundation.Collections.IIterable<Double> values);

        static DoubleVector CreateFromString(String value);
    }
}
