import "Adorners/Adorner.idl";

namespace XamlToolkit.Labs.WinUI
{
    [default_interface]
    runtimeclass ResizeElementAdorner : Adorner
    {
        ResizeElementAdorner();

        Microsoft.UI.Xaml.FrameworkElement AdornedElement{ get; };
    }
}
