import "TokenizingTextBox/TokenizingTextBoxItem.idl";

namespace XamlToolkit.WinUI.Controls
{
    [default_interface]
    runtimeclass TokenItemRemovingEventArgs
    {
        TokenItemRemovingEventArgs();

        TokenItemRemovingEventArgs(Object item, TokenizingTextBoxItem token);

        Object Item{ get; };

        TokenizingTextBoxItem Token{ get; };

        Boolean Cancel;
    }
}
