namespace XamlToolkit.WinUI.Behaviors
{
    /// <summary>
    /// Performs an fade animation on a ListView or GridView Header using composition.
    /// </summary>
	[default_interface]
    runtimeclass FadeHeaderBehavior : XamlToolkit.WinUI.Interactivity.IBehavior
    {
        FadeHeaderBehavior();
    }
}