namespace XamlToolkit.WinUI.Controls
{
    [default_interface]
    runtimeclass SuggestionRequestedEventArgs 
    {
        SuggestionRequestedEventArgs();

        String Prefix;

        String QueryText;

        Boolean Cancel{ get; };
    }
}
