namespace XamlToolkit.WinUI.Interactivity
{
    enum ComparisonConditionType
    {
        Equal,
        NotEqual,
        LessThan,
        LessThanOrEqual,
        GreaterThan,
        GreaterThanOrEqual
    };
}
